select
    order_id,
    customer_id,
    email,
    order_name,
    order_number,
    currency,
    financial_status,
    fulfillment_status,
    total_price,
    subtotal_price,
    total_tax,
    total_discounts,
    created_at_epoch,
    created_at_utc,
    cancelled_at,
    portable_extracted_at,
    _airbyte_extracted_at
from {{ ref('stg_orders') }}